title: Disjecta Membra
url: "https://mdgjohnny.github.io"

remote_theme: b2a3e8/jekyll-theme-console
style: dark

header_pages:
  - index.md
  - about.md
  - posts.md

plugins:
  - jekyll-remote-theme

markdown: kramdown
